# how zero-trust network works:
# create separate networks for each service containing only that service and uberproxy
# this way all communication goes through uberproxy, even including inter-service ones
# we currently have a geegle_unsecure network but we will migrate all of them to
# beyondcorp later
#
# for binary challenges, we are tunneling the traffic through websocket using
# cli-relay.corp.geegle.org

version: '2'
services:
  # infra
  uberproxy:
    image: gcr.io/geegle/infra/uberproxy:latest
    networks:
      beyondcorp_gae:
      beyondcorp_filesystem:
      beyondcorp_quicksort:
      beyondcorp_who_is_attacking_me:
      beyondcorp_etcpasswd:
      beyondcorp_intranet:
      beyondcorp_intern_manager:
      beyondcorp_guest_kiosk:
      beyondcorp_privatefile:
      beyondcorp_intern_project:
      beyondcorp_kix:
      beyondcorp_payroll:
      beyondcorp_game:
      beyondcorp_trycatch:
      beyondcorp_geemail_frontend:
      beyondcorp_geemail_backend:
    ports:
    - "80:80"
    - "443:443"
    dns_search:
      - corp.geegle.org
      - geegle.org

  redis:
    image: redis:latest
    networks:
      geegle_unsecure:
    dns_search:
      - corp.geegle.org
      - geegle.org

  mss:
    image: gcr.io/geegle/infra/mss:latest
    networks:
      geegle_unsecure:
    dns_search:
      - corp.geegle.org
      - geegle.org

  gae:
    image: gcr.io/geegle/infra/gae:latest
    networks:
      geegle_unsecure:
      beyondcorp_gae:
        aliases:
          - apps.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  gsmtpd:
    build: ./infra/gsmtpd
    ports:
      - "25:9999"
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  geemail_frontend:
    image: gcr.io/geegle/infra/geemail-frontend:latest
    networks:
      beyondcorp_geemail_frontend:
        aliases:
          - mail.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  geemail_backend:
    image: gcr.io/geegle/infra/geemail-backend:latest
    networks:
      beyondcorp_geemail_backend:
        aliases:
          - geemail-backend.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org


  # High school
  web-filesystem:
    image: gcr.io/geegle/highschool/web-filesystem:latest
    networks:
      beyondcorp_filesystem:
        aliases:
          - webfiles.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  misc-quicksort:
    image: gcr.io/geegle/highschool/misc-quicksort:latest
    networks:
      beyondcorp_quicksort:
        aliases:
          - quicksort.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  misc-who-is-attacking-me:
    image: gcr.io/geegle/highschool/misc-who-is-attacking-me:latest
    networks:
      beyondcorp_who_is_attacking_me:
        aliases:
          - attack-check.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  misc-etcpasswd:
    image: gcr.io/geegle/highschool/crypto-etcpasswd:latest
    networks:
      beyondcorp_etcpasswd:
        aliases:
          - sysadmin-shell.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  web-local_intranet:
    image: gcr.io/geegle/highschool/web-intranet:latest
    networks:
      beyondcorp_intranet:
        aliases:
          - intranet-browser.corp.geegle.org
      chal_intranet:
        aliases:
          - internal.docs
    dns_search:
      - corp.geegle.org
      - geegle.org

  web-intern-management:
    image: gcr.io/geegle/highschool/web-intern-account-manager:latest
    networks:
      beyondcorp_intern_manager:
        aliases:
          - intern-acc-manager.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  web-guest-kiosk:
    image: gcr.io/geegle/highschool/web-guest-kiosk:latest
    networks:
      beyondcorp_guest_kiosk:
        aliases:
          - guest.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  web-privatefile:
    image: gcr.io/geegle/highschool/web-privatefile:latest
    networks:
      beyondcorp_privatefile:
        aliases:
          - drive-lite.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  pwn-intern-project:
    image: gcr.io/geegle/highschool/pwn-intern-project:latest
    networks:
      beyondcorp_intern_project:
        aliases:
          - intern-project.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  # NewHires
  kix:
    build: ./advanced/kix
    networks:
      beyondcorp_kix:
        aliases:
          - docs.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  pwn-payroll:
    build: ./advanced/pwn-payroll
    networks:
      beyondcorp_payroll:
        aliases:
          - payroll.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  pwn-game:
    build: ./advanced/pwn-game
    networks:
      beyondcorp_game:
        aliases:
          - game.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  re-trycatch:
    build: ./advanced/re-trycatch
    networks:
      beyondcorp_trycatch:
        aliases:
          - trycatch.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

networks:
  geegle_unsecure:
  beyondcorp_gae:
  beyondcorp_filesystem:
  beyondcorp_quicksort:
  beyondcorp_who_is_attacking_me:
  beyondcorp_etcpasswd:
  beyondcorp_intranet:
  beyondcorp_intern_manager:
  beyondcorp_guest_kiosk:
  beyondcorp_privatefile:
  beyondcorp_intern_project:
  beyondcorp_kix:
  beyondcorp_payroll:
  beyondcorp_game:
  beyondcorp_trycatch:
  beyondcorp_geemail_frontend:
  beyondcorp_geemail_backend:
  chal_intranet:
