version: '2'
services:
  kix:
    build: ./kix
    networks:
      geegle_test:
  redis:
    image: redis:latest
    networks:
      geegle_test:
  mss:
    build: ./mss
    networks:
      geegle_test:
  gae:
    build: ./gae
    networks:
      geegle_test:
    ports:
    - "8056:80"

  
  
  hs-recursive:
    image: golang:1.11
    volumes:
      - ./WorkExperience/recursive_dir/generate_site.sh:/generate_site.sh
      - ./WorkExperience/recursive_dir/main.go:/main.go
    command: bash /generate_site.sh 
    ports:
      - "9000:80"

  local_intranet: 
    image: easy_ssrf
    ports:
      - "9001:80"
    hostname: internal.docs

  intern-management: 
    image: cookies
    ports:
      - "9002:80"

  etcpasswd: 
    image: etcpasswd
    ports:
      - "9003:22"
    read_only: true

  mailserver-dev:
    image: mailserver-dev
    ports:
      - "587:9999"
    read_only: true

  intern-project: 
    image: intern-project
    ports:
      - "19204:19204"
    read_only: true


networks:
  geegle_test:
