version: '2'
services:
  # infra
  redis:
    image: redis:latest
    networks:
      geegle_test:

  mss:
    build: ./mss
    networks:
      geegle_test:

  gae:
    build: ./gae
    networks:
      geegle_test:
    ports:
    - "8056:80"

  uberproxy:
    build: ./uberproxy
    networks:
      beyondcorp_filesystem:
      beyondcorp_quicksort:
      beyondcorp_who_is_attacking_me:
      beyondcorp_etcpasswd:
      beyondcorp_intranet:
      beyondcorp_intern_manager:
      beyondcorp_guest_kiosk:
      beyondcorp_privatefile:
      beyondcorp_intern_project:
      beyondcorp_kix:
      beyondcorp_payroll:
      beyondcorp_game:
      beyondcorp_trycatch:
    ports:
    - "80:80"


  # High school
  web-filesystem:
    image: golang:1.11
    volumes:
      - ./WorkExperience/web-filesystem/generate_site.sh:/generate_site.sh
      - ./WorkExperience/web-filesystem/main.go:/main.go
    command: bash /generate_site.sh
    networks:
      beyondcorp_filesystem:
        aliases:
          - webfiles.corp.geegle.org

  misc-quicksort:
    build: ./WorkExperience/misc-quicksort
    networks:
      beyondcorp_quicksort:
        aliases:
          - quicksort.corp.geegle.org
    read_only: true

  misc-who-is-attacking-me:
    build: ./WorkExperience/misc-who-is-attacking-me
    networks:
      beyondcorp_who_is_attacking_me:
        aliases:
          - attack-check.corp.geegle.org
    read_only: true

  misc-etcpasswd:
    build: ./WorkExperience/crypto-etcpasswd
    networks:
      beyondcorp_etcpasswd:
        aliases:
          - sysadmin-shell.corp.geegle.org
    read_only: true



  web-local_intranet:
    build: ./WorkExperience/web-intranet
    networks:
      beyondcorp_intranet:
        aliases:
          - intranet-browser.corp.geegle.org
      chal_intranet:
        aliases:
          - internal.docs

  web-intern-management:
    build: ./WorkExperience/web-intern-account-manager
    networks:
      beyondcorp_intern_manager:
        aliases:
          - intern-acc-manager.corp.geegle.org

  web-guest-kiosk:
    build: ./WorkExperience/web-guest-kiosk
    networks:
      beyondcorp_guest_kiosk:
        aliases:
          - guest.corp.geegle.org

  web-privatefile:
    build: ./WorkExperience/web-privatefile
    networks:
      beyondcorp_privatefile:
        aliases:
          - drive-lite.corp.geegle.org

  pwn-intern-project:
    build: ./WorkExperience/pwn-intern-project
    networks:
      beyondcorp_intern_project:
        aliases:
          - intern-project.corp.geegle.org
    read_only: true

  # NewHires
  kix:
    build: ./NewHire/kix
    networks:
      beyondcorp_kix:
        aliases:
          - docs.corp.geegle.org

  # TODO: move this outside to another separate server, listen on port 25
  pwn-mailserver-dev:
    build: ./NewHire/pwn-mailserver-dev
    ports:
      - "587:9999"
    read_only: true

  pwn-payroll:
    build: ./NewHire/pwn-payroll
    networks:
      beyondcorp_payroll:
        aliases:
          - payroll.corp.geegle.org
    read_only: true

  pwn-game:
    build: ./NewHire/pwn-game
    networks:
      beyondcorp_game:
        aliases:
          - game.corp.geegle.org
    read_only: true

  re-trycatch:
    build: ./NewHire/re-trycatch
    networks:
      beyondcorp_trycatch:
        aliases:
          - trycatch.corp.geegle.org
    read_only: true

networks:
  geegle_test:
  beyondcorp_filesystem:
  beyondcorp_quicksort:
  beyondcorp_who_is_attacking_me:
  beyondcorp_etcpasswd:
  beyondcorp_intranet:
  beyondcorp_intern_manager:
  beyondcorp_guest_kiosk:
  beyondcorp_privatefile:
  beyondcorp_intern_project:
  beyondcorp_kix:
  beyondcorp_payroll:
  beyondcorp_game:
  beyondcorp_trycatch:
  chal_intranet:
