version: '2'
services:
  kix:
    build: ./kix
    networks:
      geegle_test:
  redis:
    image: redis:latest
    networks:
      geegle_test:
  mss:
    build: ./mss
    networks:
      geegle_test:
  gae:
    build: ./gae
    networks:
      geegle_test:
    ports:
    - "8056:80"

  mailserver-dev:
    image: mailserver-dev
    ports:
      - "587:9999"
    read_only: true
  intern-project: 
    image: intern-project
    ports:
      - "19204:19204"
    read_only: true


networks:
  geegle_test:
