# how zero-trust network works:
# create separate networks for each service containing only that service and uberproxy
# this way all communication goes through uberproxy, even including inter-service ones
# we currently have a geegle_unsecure network but we will migrate all of them to
# beyondcorp later
#
# for binary challenges, we are tunneling the traffic through websocket using
# cli-relay.corp.geegle.org

version: '2'
services:
  # infra
  uberproxy:
    image: gcr.io/geegle/infra/uberproxy:latest
    networks:
      beyondcorp_gae:
      beyondcorp_sffe:
      beyondcorp_who_is_attacking_me:
      beyondcorp_guest_kiosk:
      beyondcorp_intern_project:
      beyondcorp_kix:
      beyondcorp_seclearn:
      beyondcorp_pasteweb:
      beyondcorp_payroll:
      beyondcorp_game:
      beyondcorp_geelang:
      beyondcorp_trycatch:
      beyondcorp_geemail_frontend:
      beyondcorp_geemail_backend:
      beyondcorp_memegen:
      beyondcorp_flatearth:
      beyondcorp_employees:
      beyondcorp_shell:
    ports:
    - "80:80"
    - "443:443"
    dns_search:
      - corp.geegle.org
      - geegle.org

  redis:
    image: redis:latest
    networks:
      geegle_unsecure:
    dns_search:
      - corp.geegle.org
      - geegle.org

  mss:
    image: gcr.io/geegle/infra/mss:latest
    networks:
      geegle_unsecure:
    dns_search:
      - corp.geegle.org
      - geegle.org

  gae:
    image: gcr.io/geegle/infra/gae:latest
    networks:
      geegle_unsecure:
      beyondcorp_gae:
        aliases:
          - apps.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  sffe:
    image: gcr.io/geegle/infra/sffe:latest
    networks:
      beyondcorp_sffe:
        aliases:
          - sffe.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  gsmtpd:
    build: ./infra/gsmtpd
    ports:
      - "25:9999"
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  geemail_frontend:
    image: gcr.io/geegle/infra/geemail-frontend:latest
    networks:
      beyondcorp_geemail_frontend:
        aliases:
          - mail.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  geemail_backend:
    image: gcr.io/geegle/infra/geemail-backend:latest
    networks:
      beyondcorp_geemail_backend:
        aliases:
          - geemail-backend.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org


  # High school
  misc-who-is-attacking-me:
    image: gcr.io/geegle/chals/ir/who-is-attacking-me:latest
    networks:
      beyondcorp_who_is_attacking_me:
        aliases:
          - attack-check.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  web-guest-kiosk:
    image: gcr.io/geegle/chals/web/guest:latest
    networks:
      beyondcorp_guest_kiosk:
        aliases:
          - guest.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  pwn-intern-project:
    image: gcr.io/geegle/chals/pwn/intern-project:latest
    networks:
      beyondcorp_intern_project:
        aliases:
          - intern-project.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  # NewHires
  web_kix:
    image: gcr.io/geegle/chals/web/kix:latest
    networks:
      beyondcorp_kix:
        aliases:
          - docs.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  web_seclearn:
    image: gcr.io/geegle/chals/web/seclearn:latest
    networks:
      beyondcorp_seclearn:
        aliases:
          - seclearn.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  web_employees:
    image: gcr.io/geegle/chals/web/employees:latest
    networks:
      beyondcorp_employees:
        aliases:
          - employees.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  general-shell:
    image: gcr.io/geegle/chals/pwn/shell:latest
    networks:
      beyondcorp_shell:
        aliases:
          - shell.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org



  web_pasteweb:
    image: gcr.io/geegle/chals/web/pasteweb:latest
    networks:
      beyondcorp_pasteweb:
        aliases:
          - pasteweb.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  web_memegen:
    image: gcr.io/geegle/chals/web/memegen:latest
    networks:
      beyondcorp_memegen:
        aliases:
          - memegen.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  web_flatearth:
    image: gcr.io/geegle/chals/web/flatearth:latest
    networks:
      beyondcorp_flatearth:
        aliases:
          - flatearth.corp.geegle.org
    dns_search:
      - corp.geegle.org
      - geegle.org

  pwn-payroll:
    image: gcr.io/geegle/chals/pwn/payroll:latest
    networks:
      beyondcorp_payroll:
        aliases:
          - payroll.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  pwn-game:
    image: gcr.io/geegle/chals/pwn/game:latest
    networks:
      beyondcorp_game:
        aliases:
          - game.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  pwn-geelang:
    image: gcr.io/geegle/chals/pwn/geelang:latest
    networks:
      beyondcorp_geelang:
        aliases:
          - geelang.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

  re-trycatch:
    image: gcr.io/geegle/chals/re/trycatch:latest
    networks:
      beyondcorp_trycatch:
        aliases:
          - onboarding.corp.geegle.org
    read_only: true
    dns_search:
      - corp.geegle.org
      - geegle.org

networks:
  geegle_unsecure:
  beyondcorp_gae:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.0/29
  beyondcorp_who_is_attacking_me:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.24/29
  beyondcorp_guest_kiosk:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.56/29
  beyondcorp_intern_project:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.72/29
  beyondcorp_kix:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.80/29
  beyondcorp_seclearn:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.88/29
  beyondcorp_pasteweb:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.96/29
  beyondcorp_payroll:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.104/29
  beyondcorp_game:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.112/29
  beyondcorp_geelang:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.120/29
  beyondcorp_trycatch:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.128/29
  beyondcorp_geemail_frontend:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.136/29
  beyondcorp_geemail_backend:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.144/29
  beyondcorp_memegen:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.152/29
  beyondcorp_flatearth:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.160/29
  beyondcorp_sffe:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.168/29
  beyondcorp_employees:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.176/29
  beyondcorp_shell:
    ipam:
      driver: default
      config:
        - subnet: 100.88.66.184/29
  chal_intranet:
