# how zero-trust network works:
# create separate networks for each service containing only that service and uberproxy
# this way all communication goes through uberproxy, even including inter-service ones
# we currently have a geegle_unsecure network but we will migrate all of them to
# beyondcorp later

version: '2'
services:
  kix:
    build: ./kix
    networks:
      geegle_unsecure:
  redis:
    image: redis:latest
    networks:
      geegle_unsecure:
  mss:
    build: ./mss
    networks:
      geegle_unsecure:
  gae:
    build: ./gae
    networks:
      geegle_unsecure:
    ports:
    - "8056:80"
  uberproxy:
    build: ./uberproxy
    networks:
      beyondcorp_geemail_frontend:
      beyondcorp_geemail_backend:
    ports:
    - "80:80"
  geemail_frontend:
    build: ./geemail-frontend
    networks:
      beyondcorp_geemail_frontend:
        aliases:
          - mail.corp.geegle.org
  geemail_backend:
    build: ./geemail-backend
    networks:
      beyondcorp_geemail_backend:
        aliases:
          - geemail-backend.corp.geegle.org
networks:
  geegle_unsecure:
  beyondcorp_geemail_frontend:
  beyondcorp_geemail_backend:
