load("//tools:challenges_list.bzl", "challenges_list")

challenges_list(
    name = "infra_jsonnet",
    visibility = ["//visibility:public"],
    deps = [
        "//infra/cli-relay:challenge",
        "//infra/gaia:challenge",
        "//infra/geemail-backend:challenge",
        "//infra/geemail-frontend:challenge",
        "//infra/gsmtpd:challenge",
        "//infra/mss:challenge",
        "//infra/redis:challenge",
        "//infra/requestz:challenge",
        "//infra/scoreboard:challenge",
        "//infra/sffe:challenge",
        "//infra/xssbot:challenge",
    ],
)
