steps:
  - command: "git-crypt unlock /g3.key"
    label: "Decrypt Git"

  - wait

  - command: "bazel run //:gazelle -- --mode=diff || (echo \"ERROR: Bazel files out-of-date, please run \\`bazel run :gazelle\\`\" >&2; exit 1)"
    label: "Golang Bazel Lint"

  - wait

  - command: "bazel run //:buildifier_check || (echo \"ERROR: Bazel files not formatted, please run \\`bazel run :buildifier\\`\" >&2; exit 1)"
    label: "Bazel BUILD Lint"

  - wait

  - command: "bazel build //:all_containers || (echo \"ERROR: Bazel build failed\" >&2; exit 1)"
    label: "Containers BUILD"

  - block: "Confirmation for Pushing to GCR"
    branches: "master"

  - command: "bazel run //:all_containers_push || (echo \"ERROR: Bazel push failed\" >&2; exit 1)"
    label: "Push"
    branches: "master"
