steps:
  - command: "git-crypt unlock /g3.key"
    label: "Decrypt Git"

  - wait

  - command: ".buildkite/ci.sh"
    label: "CI Script"

  - wait

  - command: "bazel run //:all_containers_push || (echo \"ERROR: Bazel push failed\" >&2; exit 1)"
    label: "Push"
    branches: "master"
