load("//tools:challenges_list.bzl", "challenges_list")

challenges_list(
    name = "challenges_jsonnet",
    visibility = ["//visibility:public"],
    deps = [
        "//chals/crypto/magic:challenge",
        "//chals/emails/intro:challenge",
        "//chals/emails/newsletter:challenge",
        "//chals/ir/intercepted:challenge",
        "//chals/ir/who-is-attacking-me:challenge",
        "//chals/pwn/game:challenge",
        "//chals/pwn/geelang:challenge",
        "//chals/pwn/intern-project:challenge",
        "//chals/pwn/payroll:challenge",
        "//chals/pwn/shell:challenge",
        "//chals/re/tellGeegle:challenge",
        "//chals/web/docs:challenge",
        "//chals/web/employees:challenge",
        "//chals/web/flatearth:challenge",
        "//chals/web/guest:challenge",
        "//chals/web/memegen:challenge",
        "//chals/web/pasteweb:challenge",
        "//chals/web/search:challenge",
        "//chals/web/seclearn:challenge",
    ],
)
