load("//tools:challenges_list.bzl", "challenges_list")

challenges_list(
    name = "challenges_jsonnet",
    visibility = ["//visibility:public"],
    deps = [
        "//chals/pwn/geelang:challenge",
        "//chals/web/seclearn:challenge",
    ],
)
