// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileRequest struct {
	Filename  string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Timestamp uint32 `protobuf:"fixed32,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LogInfo   string `protobuf:"bytes,3,opt,name=log_info,json=logInfo,proto3" json:"log_info,omitempty"`
	// NOTES(adamyi@):
	// i mean... what harm can it do if we just put random large number here
	// it's nice since we can still use 4, 5, 6, etc for other things that might
	// come in the future, since I'd like trace_id to be the last item.
	// I like this idea since it sounds really extensible.
	TraceId              int32    `protobuf:"varint,48000,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

func (m *FileRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileRequest) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *FileRequest) GetLogInfo() string {
	if m != nil {
		return m.LogInfo
	}
	return ""
}

func (m *FileRequest) GetTraceId() int32 {
	if m != nil {
		return m.TraceId
	}
	return 0
}

func init() {
	proto.RegisterType((*FileRequest)(nil), "main.FileRequest")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xaa, 0xe7, 0xe2,
	0x76, 0xcb, 0xcc, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe2, 0xe2, 0x48,
	0xcb, 0xcc, 0x49, 0xcd, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3,
	0x85, 0x64, 0xb8, 0x38, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x24, 0x98, 0x14,
	0x18, 0x35, 0xd8, 0x83, 0x10, 0x02, 0x42, 0x92, 0x5c, 0x1c, 0x39, 0xf9, 0xe9, 0xf1, 0x99, 0x79,
	0x69, 0xf9, 0x12, 0xcc, 0x60, 0x9d, 0xec, 0x39, 0xf9, 0xe9, 0x9e, 0x79, 0x69, 0xf9, 0x42, 0xd2,
	0x5c, 0x1c, 0x25, 0x45, 0x89, 0xc9, 0xa9, 0xf1, 0x99, 0x29, 0x12, 0x0d, 0xdf, 0x41, 0x3a, 0x59,
	0x83, 0xd8, 0xc1, 0x22, 0x9e, 0x29, 0x49, 0x6c, 0x60, 0xd7, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x3b, 0xfd, 0x85, 0x7e, 0x9b, 0x00, 0x00, 0x00,
}
